# Generated by Django 6.0.4 on 2026-05-19 06:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogmodel_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogmodel',
            new_name='Blog',
        ),
    ]
